### ISSUE TITLE
Consider moving out installation script

### ISSUE THREAD

**Issue by cyberartemio** [K3YOMI/Wall-of-Flippers#17]
Hello,
I think that installation logic can be moved outside of the main script. With high probability, installation is run only one time on the system so it is better to have a different script (like `scripts/setup.py`) where are executed the same steps that are executed currently in `install_dependencies` branch.

Also, since the script can be installed manually it makes more sense to move the installation outside.

What do you think about it?

**Comment by K3YOMI** [comment]
Hmm.  I'll write that down! Thank you!

**Comment by cyberartemio** [comment]
If you are busy, I can work on this and then open a PR

**Comment by K3YOMI** [comment]
I could handle this for sure!
