### ISSUE TITLE
Stated pybluez install error

### ISSUE THREAD

**Issue by JD-2006** [K3YOMI/Wall-of-Flippers#19]
When using: python3 -m pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez#egg=pybluez

ERROR: Invalid requirement: 'pybluez#egg=pybluez'

But using: python3 -m pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez

Using legacy 'setup.py install' for pybluez, since package 'wheel' is not installed.

worked.  Maybe add wheel to requirements.txt to simplify install?

**Comment by K3YOMI** [comment]
> When using: python3 -m pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez#egg=pybluez


Specified twice:  `#egg=pybluez` was specified twice
