### ISSUE TITLE
[!] Wall of Flippers >> Error: Failed to scan for BLE devices >> [WinError -2147020577] The device is not ready for use

### ISSUE THREAD

**Issue by JustLeska** [K3YOMI/Wall-of-Flippers#21]
![image](https://github.com/K3YOMI/Wall-of-Flippers/assets/82216890/e8219497-4b41-4e93-a550-89e42d0165c8)

**Comment by K3YOMI** [comment]
https://github.com/hbldh/bleak/issues/792
