### ISSUE TITLE
Pwnagotchi install failed

### ISSUE THREAD

**Issue by nerdyjedi** [K3YOMI/Wall-of-Flippers#22]
Service does not start:

`root@pwnagotchi:~# systemctl status wof
● wof.service - WallofFlippers - A simple and easy way to find Flipper Zero Devices and Bluetooth Low Energy Based Attacks
   Loaded: loaded (/etc/systemd/system/wof.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2024-01-22 11:32:37 EST; 2min 6s ago
  Process: 870 ExecStart=/root/Wall-of-Flippers/.venv/bin/python /root/Wall-of-Flippers/WallofFlippers.py wof -d 0 (code=exited, status=1/FAILURE)
 Main PID: 870 (code=exited, status=1/FAILURE)

Jan 22 11:32:36 pwnagotchi wof[870]: TERM environment variable not set.
Jan 22 11:32:36 pwnagotchi wof[870]: 
Jan 22 11:32:36 pwnagotchi wof[870]: Traceback (most recent call last):
Jan 22 11:32:36 pwnagotchi wof[870]:   File "/root/Wall-of-Flippers/WallofFlippers.py", line 262, in <module>
Jan 22 11:32:36 pwnagotchi wof[870]:     library.print_ascii_art("Uh oh, it seems like you have not setup your virtual environment yet!")
Jan 22 11:32:36 pwnagotchi wof[870]:   File "/root/Wall-of-Flippers/utils/wof_library.py", line 98, in print_ascii_art
Jan 22 11:32:36 pwnagotchi wof[870]:     print(cache.wof_data['ascii_normal'].replace("[RANDOM_QUOTE]", r_quote))
Jan 22 11:32:36 pwnagotchi wof[870]: KeyError: 'ascii_normal'
Jan 22 11:32:37 pwnagotchi systemd[1]: wof.service: Main process exited, code=exited, status=1/FAILURE
Jan 22 11:32:37 pwnagotchi systemd[1]: wof.service: Failed with result 'exit-code'.
`

**Comment by K3YOMI** [comment]
@cyberartemio
