### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by HelpNetSecurity** [K3YOMI/Wall-of-Flippers#24]
Hi team,

I'm trying to contact the core devs for this project. I want to do an article about it, and it would be great to get someone to answer a few questions for the story over email. Interested?

**Comment by K3YOMI** [comment]
Hello @HelpNetSecurity , 
 
I sadly can't do questions over email. However; I am free to answer any questions in the public discord server listed in the documentation. 

https://discord.gg/jC2gxQjs
