### ISSUE TITLE
Failed to scan for BLE devices

### ISSUE THREAD

**Issue by baseattackforce** [K3YOMI/Wall-of-Flippers#25]
I have all 4 dependencies checked, and when I press 1 it gives me:
[#]	[HCI DEVICE]
--------------------------------------------------------------------------------
0       hci0                              

and just sits there. When i try to type anything in after, i get the error.

[!] Wall of Flippers >> Error: Failed to scan for BLE devices >> Helper exited
root@debian:/home/admin/Wall-of-Flippers# 

I'm not sure if I'm supposed to wait after pressing 1 for a device to pop up, or if there is a real bug. I'm new to linux, so any help would be appreciated, thanks! (running on debian 12)

**Comment by K3YOMI** [comment]
https://github.com/IanHarvey/bluepy/issues/223

**Comment by baseattackforce** [comment]
I'm not very knowledgeable with linux in general, I saw at the end that apparently 1.1.4 fixed the issue but it still happens for me in the latest version of bluepy.
