### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by TheAnonymousXII** [K3YOMI/Wall-of-Flippers#26]
You should make a version of the application for Android. I know Bluetooth LE Spam is a thing but it has features that I don't necessarily need to have and isn't as powerful for detection.

**Comment by K3YOMI** [comment]
Thank you for your feedback and suggestion regarding the development of an Android version of the application. While I would like to start this type of project, I don't have the time anymore.
However, I do support other developers using this project as a base for other devices. Example being the Wall of Flippers Pwnagotchi plugin (https://github.com/cyberartemio/wof-pwnagotchi-plugin)

**Comment by TheAnonymousXII** [comment]
I am so sorry to hear that you don't have any time to do anything fun any more, and hope you best of luck in college (as told on your profile). Thanks for letting me know about the plugin, I'm sure it will come in handy in the future as well as this repo. If you find anything else or eventually get the time and start the project, you can contact me at contact@theanonymousxi.anonaddy.me Wish you well, TAXI

**Comment by K3YOMI** [comment]
👍
