### ISSUE TITLE
Installing on the Pi 5 (Debain) Doesn't work. 

### ISSUE THREAD

**Issue by ErikLavr** [K3YOMI/Wall-of-Flippers#27]
Hello! After i run 

sudo apt-get install libglib2.0-dev
sudo apt-get install python3-bluez
python3 -m venv .venv
source .venv/bin/activate
################## PACKAGES ########################
# requirement.txt method
python3 -m pip install -r requirements.txt
# command method
python3 -m pip install bluepy
python3 -m pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez
################## PACKAGES ########################
deactivate

It prints to the console about some error or something (I couldn't replicate it right now because it worked??) But yeah when i run Wall of flippers it just says [!] Wall of Flippers >> Error: Failed to scan for BLE devices >> Failed to execute management command 'le on' (code: 17, error: Invalid Index). Does anyone know how to fix this? Thanks! (I tried on Ubuntu too and it didn't work sooo yeah)

**Comment by ErikLavr** [comment]
Forgot to format all of the things. Whoops

**Comment by K3YOMI** [comment]
external or internal BT?
using a VM?

**Comment by ErikLavr** [comment]
Nvm. I fixed it tho.
