### ISSUE TITLE
got errors when running on raspberry-pi

### ISSUE THREAD

**Issue by NARX00** [K3YOMI/Wall-of-Flippers#6]
Traceback (most recent call last):
  File "/home/xxx/Wall-of-Flippers/WallofFlippers.py", line 576, in <module>
    selection_box = library.__init__()
  File "/home/xxx/Wall-of-Flippers/WallofFlippers.py", line 305, in __init__
    library.ascii_art("Please Select an option to continue")  # or the appropriate encoding
  File "/home/xxx/Wall-of-Flippers/WallofFlippers.py", line 340, in ascii_art
    print(s_ascii.replace("[RANDOM_QUOTE]", r_quote).encode('utf-8').decode('utf-8', 'ignore'))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 728-729: ordinal not in range(256)

**Comment by K3YOMI** [comment]
Did you modify the code in any way?


```py
    def ascii_art(str_text): # This function displays ASCII art of a dolphin and clears the console.
        os.system('cls' if wof_data['system_type'] == 'nt' else 'clear')
        s_ascii = wof_data['ascii']
        if library.in_ctf():
            # If CTF mode is enabled, switch to the CTF version of the ASCII art.
            s_ascii = wof_data['ascii_ctf']
        r_quote = random.choice(wof_data['dolphin_thinking']) if not str_text else str_text
        print(s_ascii.replace("[RANDOM_QUOTE]", r_quote))
 ```

**Comment by NARX00** [comment]
nope, just cloned and ran the code

**Comment by K3YOMI** [comment]
> nope, just cloned and ran the code

Hmmm, can you try to re-clone the latest build and see if that works?

**Comment by NARX00** [comment]
still get the same errors

**Comment by K3YOMI** [comment]
> still get the same errors

Are you running off the official or someone's fork? because this line of code: 
```py
print(s_ascii.replace("[RANDOM_QUOTE]", r_quote).encode('utf-8').decode('utf-8', 'ignore'))
```
doesn't exist

**Comment by NARX00** [comment]
you right there was other code, but still have the same issue.

Traceback (most recent call last):
  File "/home/alexpi/Wall-of-Flippers/WallofFlippers.py", line 569, in <module>
    selection_box = library.__init__()
  File "/home/alexpi/Wall-of-Flippers/WallofFlippers.py", line 305, in __init__
    library.ascii_art("Please Select an option to continue")
  File "/home/alexpi/Wall-of-Flippers/WallofFlippers.py", line 339, in ascii_art
    print(s_ascii.replace("[RANDOM_QUOTE]", r_quote))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 728-729: ordinal not in range(256)

**Comment by K3YOMI** [comment]
Try replacing the line with this: 
```py
print(s_ascii.replace("[RANDOM_QUOTE]", r_quote).encode('utf-8'))
```
at line 339

**Comment by NARX00** [comment]
it worked.

b' \n                               YAao,                            \n                                 Y8888b,                        Created By: Kiyomi + Emilia (jbohack)\n                               ,oA8888888b,                     Emilia: https://ko-fi.com/emilia0001\n                         ,aaad8888888888888888bo,               Kiyomi: https://ko-fi.com/k3yomi\n                      ,d888888888888888888888888888b,           Github: github.com/K3YOMI/Wall-of-Flippers    \n                    ,888888888888888888888888888888888b,            \n                   d8888888888888888888888888888888888888,        "Please Select an option to continue"             \n                  d888888888888888888888888888888888888888b     \xf0\x9f\x97\xaf\xef\xb8\x8f            \n                 d888888P\'                    `Y88888888\xea\x99\xa8 \\,  \xf0\x9f\x97\xaf\xef\xb8\x8f           \n                 88888P\'                    Ybaaaa888888  \xea\x99\xa8 l          \n                a8888\'                      `Y8888P\' `V888888    \n              d8888888a                                `Y8888           \n             AY/\'\' `\\Y8b                                 ``Y8b\n             Y\'      `YP                                    ~~\n     _       __      ____         ____   _________                           \n    | |     / /___ _/ / /  ____  / __/  / ____/ (_)___  ____  ___  __________\n    | | /| / / __ `/ / /  / __ \\/ /_   / /_  / / / __ \\/ __ \\/ _ \\/ ___/ ___/\n    | |/ |/ / /_/ / / /  / /_/ / __/  / __/ / / / /_/ / /_/ /  __/ /  (__  ) \n    |__/|__/\\__,_/_/_/   \\____/_/    /_/   /_/_/ .___/ .___/\\___/_/  /____/ \n                                              /_/   /_/                    v3.0.0\n'
[X] Bleak is not installed yet, ignore if you are running under a linux system.
Traceback (most recent call last):
  File "/home/xxx/Wall-of-Flippers/WallofFlippers.py", line 570, in <module>
    selection_box = library.__init__()
  File "/home/xxx/Wall-of-Flippers/WallofFlippers.py", line 314, in __init__
    print(f"[\u2713] Requests is installed")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 1: ordinal not in range(256)

still have an issue on lines 314 and 570

**Comment by K3YOMI** [comment]
Not quite, ascii art is really messed up now. Give me a second.

**Comment by K3YOMI** [comment]
> it worked.
> 
> b' \n YAao, \n Y8888b, Created By: Kiyomi + Emilia (jbohack)\n ,oA8888888b, Emilia: [https://ko-fi.com/emilia0001\n](https://ko-fi.com/emilia0001%5Cn) ,aaad8888888888888888bo, Kiyomi: [https://ko-fi.com/k3yomi\n](https://ko-fi.com/k3yomi%5Cn) ,d888888888888888888888888888b, Github: github.com/K3YOMI/Wall-of-Flippers \n ,888888888888888888888888888888888b, \n d8888888888888888888888888888888888888, "Please Select an option to continue" \n d888888888888888888888888888888888888888b \xf0\x9f\x97\xaf\xef\xb8\x8f \n d888888P' `Y88888888\xea\x99\xa8 \\, \xf0\x9f\x97\xaf\xef\xb8\x8f \n 88888P\' Ybaaaa888888 \xea\x99\xa8 l \n a8888\' `Y8888P' `V888888 \n d8888888a `Y8888 \n AY/'' `` \\Y8b ``Y8b\n Y\' ``YP ~~\n _ __ ____ ____ _________ \n | | / /___ _/ / / ____ / **/ / _**_/ (_)**_ ____ ___ __________\n | | /| / / __ `/ / / / __ \/ /_ / /_ / / / __ \/ __ \/ _ \/ _/ ___/\n | |/ |/ / /_/ / / / / /_/ / __/ / __/ / / / /_/ / /_/ / / / ( ) \n |/|**/\__,_/_/_/ \____/_/ /_/ /_/_/ ._**/ .**_/\**_/_/ /**__/ \n /_/ /_/ v3.0.0\n' [X] Bleak is not installed yet, ignore if you are running under a linux system. Traceback (most recent call last): File "/home/xxx/Wall-of-Flippers/WallofFlippers.py", line 570, in selection_box = library.**init**() File "/home/xxx/Wall-of-Flippers/WallofFlippers.py", line 314, in **init** print(f"[\u2713] Requests is installed") UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 1: ordinal not in range(256)
> 
> still have an issue on lines 314 and 570

Try latest commit and see if that works

**Comment by NARX00** [comment]
yep, much better now :) 

     _       __      ____         ____   _________                           
    | |     / /___ _/ / /  ____  / __/  / ____/ (_)___  ____  ___  __________
    | | /| / / __ `/ / /  / __ \/ /_   / /_  / / / __ \/ __ \/ _ \/ ___/ ___/
    | |/ |/ / /_/ / / /  / /_/ / __/  / __/ / / / /_/ / /_/ /  __/ /  (__  ) 
    |__/|__/\__,_/_/_/   \____/_/    /_/   /_/_/ .___/ .___/\___/_/  /____/ 
                                              /_/   /_/                    v3.0.0
[ ] Bleak is not installed yet, ignore if you are running under a linux system.
[X] Requests is installed
[X] Bluepy is installed


[#]	[ACTION]			  [DESCRIPTION]
Traceback (most recent call last):
  File "/home/alexpi/Wall-of-Flippers/WallofFlippers.py", line 574, in <module>
    selection_box = library.__init__()
  File "/home/alexpi/Wall-of-Flippers/WallofFlippers.py", line 327, in __init__
    print("\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-96: ordinal not in range(256)

**Comment by K3YOMI** [comment]
> yep, much better now :) 
> 
> 
> 
>      _       __      ____         ____   _________                           
> 
>     | |     / /___ _/ / /  ____  / __/  / ____/ (_)___  ____  ___  __________
> 
>     | | /| / / __ `/ / /  / __ \/ /_   / /_  / / / __ \/ __ \/ _ \/ ___/ ___/
> 
>     | |/ |/ / /_/ / / /  / /_/ / __/  / __/ / / / /_/ / /_/ /  __/ /  (__  ) 
> 
>     |__/|__/\__,_/_/_/   \____/_/    /_/   /_/_/ .___/ .___/\___/_/  /____/ 
> 
>                                               /_/   /_/                    v3.0.0
> 
> [ ] Bleak is not installed yet, ignore if you are running under a linux system.
> 
> [X] Requests is installed
> 
> [X] Bluepy is installed
> 
> 
> 
> 
> 
> [#]	[ACTION]			  [DESCRIPTION]
> 
> Traceback (most recent call last):
> 
>   File "/home/alexpi/Wall-of-Flippers/WallofFlippers.py", line 574, in <module>
> 
>     selection_box = library.__init__()
> 
>   File "/home/alexpi/Wall-of-Flippers/WallofFlippers.py", line 327, in __init__
> 
>     print("\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501")
> 
> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-96: ordinal not in range(256)
> 
> 

Great, I removed all custom chars to avoid this in the future. Thank you!

**Comment by NARX00** [comment]
Thank you as well! Your project is truly impressive, and I sincerely appreciate the effort you and your team have put into its development. Wishing you a wonderful holiday season and a joyous New Year ahead!
