### ISSUE TITLE
Unable to complete install

### ISSUE THREAD

**Issue by mmiller7** [K3YOMI/Wall-of-Flippers#7]
I'm on Linux Mint (Ubuntu 22.04-LTS based) and the `pip install` commands do not work to install the dependencies you mentioned.  It sounds like pip is disabled due to it frequently breaking apt and other system critical components.

Is there an alternative method to manually download and place whatever dependencies, or a different package name thru the normal apt package managers?

```
$ pip3 install bluepy
Traceback (most recent call last):
  File "/home/user/.local/bin/pip3", line 7, in <module>
    from pip._internal import main
ModuleNotFoundError: No module named 'pip'
$ sudo pip3 install bluepy
[sudo] password for user:          
sudo: pip3: command not found
```

**Comment by K3YOMI** [comment]
You could do `sudo apt-get install python3-packagenamehere` instead and see if that works for you.

**Comment by mmiller7** [comment]
> You could do `sudo apt-get install python3-packagenamehere` instead and see if that works for you. However, that may not work due to not being available in the default Ubuntu/MInt repositories. If no module is found the only way I could think of is installing through the git itself.
> 
> ```
> git clone https://github.com/IanHarvey/bluepy.git
> cd bluepy
> sudo pip3 install .
> ```

I have tried looking for a python3-bluepy but haven't found anywhere that suggests what it is named if such a thing exists.

Trying to clone and then do a pip3 install it fails `sudo: pip3: command not found` even though pip/pip3 exists as a normal user.

**Comment by mmiller7** [comment]
I also had a friend who is better than I am at Python try and he suggested using a venv, which I after running the venv I can do a pip3 install successfully, but WallOfFlippers still claims its not installed even though it is.

**Comment by K3YOMI** [comment]
> I also had a friend who is better than I am at Python try and he suggested using a venv, which I after running the venv I can do a pip3 install successfully, but WallOfFlippers still claims its not installed even though it is.

Is venv being used with sudo or not?
Wall of Flippers requires sudo to run due to the BLE python package (bluepy).
If the command venv command wasn't initially ran in sudo, I could see WoF not recognize the packages required as it's trying to import the packages but fails with the exception of not being able to import said package.

**Comment by mmiller7** [comment]
> > I also had a friend who is better than I am at Python try and he suggested using a venv, which I after running the venv I can do a pip3 install successfully, but WallOfFlippers still claims its not installed even though it is.
> 
> Is venv being used with sudo or not? Wall of Flippers requires sudo to run due to the BLE python package (bluepy). If the command venv command wasn't initially ran in sudo, I could see WoF not recognize the packages required as it's trying to import the packages but fails with the exception of not being able to import said package.

The venv wasn't, but yes I was running the script with sudo as indicated.

**Comment by K3YOMI** [comment]
Hmmm, let me figuring something out real quick.

**Comment by K3YOMI** [comment]
I'm going to see if moving to venv will be a better idea instead of using pip. Let me do more testing to see if this switch would be optimal

**Comment by K3YOMI** [comment]
> > > I also had a friend who is better than I am at Python try and he suggested using a venv, which I after running the venv I can do a pip3 install successfully, but WallOfFlippers still claims its not installed even though it is.
> > 
> > 
> > Is venv being used with sudo or not? Wall of Flippers requires sudo to run due to the BLE python package (bluepy). If the command venv command wasn't initially ran in sudo, I could see WoF not recognize the packages required as it's trying to import the packages but fails with the exception of not being able to import said package.
> 
> The venv wasn't, but yes I was running the script with sudo as indicated.

Decided to switch to virtual env. Seems a lot cooler and well managed. Just have to add a few things like a shell script to automatically activate the env and start wof at the same time


Something like: 
-------
**wof.sh**
```bash
source .venv/bin/activate
python3 WallofFlippers.py
```

**Comment by K3YOMI** [comment]
Try running the latest commit. This fully supports the use of .venv as it's now required. Documentation has also been updated with changes with .venv. If you would like, you can run Wall-of-Flippers.py once and it will auto install the .venv folder and files included. Additionally, you will need to run the installer in the python script (selection 4) if you want the easy method after implementing .venv

**Comment by mmiller7** [comment]
I did get farther now - and using "sudo bash wof.sh" it correctly finds the venv and detects all the dependencies now.

Note that it does NOT work with `sudo python3 WallOfFlippers.py` rather it seems I must use `sudo bash wof.sh`

With the venv now detected running `sudo bash wof.sh`:
```
    | |     / /___ _/ / /  ____  / __/  / ____/ (_)___  ____  ___  __________
    | | /| / / __ `/ / /  / __ \/ /_   / /_  / / / __ \/ __ \/ _ \/ ___/ ___/
    | |/ |/ / /_/ / / /  / /_/ / __/  / __/ / / / /_/ / /_/ /  __/ /  (__  ) 
    |__/|__/\__,_/_/_/   \____/_/    /_/   /_/_/ .___/ .___/\___/_/  /____/ 
                                              /_/   /_/                    v3.0.0
[ ] Bleak is installed
[X] Bluepy is installed
[X] Requests is installed
[X] Bluetooth is installed


[#]	[ACTION]			  [DESCRIPTION]
-------------------------------------------------------------------------------------------------
1       Wall of Flippers                  Wall of Flippers (Default)
2       Capture the Flippers (IN DEV)     Can you capture the most flippers and top the leaderboard? This is still in development. Hosting is not available right now.
3       Advertise Bluetooth Packets       Advertise Bluetooth Packets (Linux Support Only)
4       Auto-Install                      Install dependencies for Wall of Flippers (Windows / (APT) Debian Linux)
5       Exit                              ....

[?] Wall of Flippers >> 
```


And then I can detect things now! - interesting it claims some things I think are normal, I believe might be the Govee thermometers around the house.
```
Latest Forbidden Advertisements..: 1
Latest Advertisements............: 423
Most Common Advertisement........: 0000ec88-0000-1000-8000-00805f9b34fb (54 packets) (6 unique addresses)


[!] Wall of Flippers >> These packets may not be related to the Flipper Zero.

[NAME]					[ADDR]		   [PACKET]
-----------------------------------------------------------------------------------------------
BLE_WINDOWS_SWIFT_PAIR_SHORT		10:dc:b6:eb:ca:3e  0600030080
SUSPICIOUS_ADVERTISEMENT		6 Unique Addresses  0000ec88-0000-1000-8000-00805f9b34fb

Total Online.....................: 0
Total Offline....................: 0


[FLIPPER]        [ADDR]        		[FIRST]        [LAST]	        [RSSI]        	[Detection]        
----------------------------------------------------------------------------------------------------
                                        No devices detected                                         
```

**Comment by mmiller7** [comment]
Interesting trivia also, while it does correctly identify a Flipper (including its "name"), it does not seem to identify the source of an Android app BLE spam generator (shows suspicious packets, but not the source).  I'm guessing that may be a work in progress thing (or maybe its not possible to get a source MAC to triangulate in on if its being randomized?)

```
[!] Wall of Flippers >> These packets may not be related to the Flipper Zero.

[NAME]					[ADDR]		   [PACKET]
-----------------------------------------------------------------------------------------------
BLE_WINDOWS_SWIFT_PAIR_SHORT		10:dc:b6:eb:ca:3e  0600030080
BLE_ANDROID_DEVICE_CONNECT		79:78:e4:81:3b:ee  2cfee4e457
BLE_ANDROID_DEVICE_CONNECT		4a:a2:e0:eb:3d:bc  2cfe8c4236
BLE_ANDROID_DEVICE_CONNECT		6e:2c:04:34:c4:87  2cfe0b0000
BLE_ANDROID_DEVICE_CONNECT		5c:eb:b1:14:62:49  2cfe0c0000
BLE_ANDROID_DEVICE_CONNECT		55:f7:11:bc:f0:3f  2cfe00000c
BLE_ANDROID_DEVICE_CONNECT		57:55:15:46:54:c1  2cfe000006
BLE_ANDROID_DEVICE_CONNECT		43:da:44:7e:43:56  2cfe060000
BLE_ANDROID_DEVICE_CONNECT		41:13:cf:fb:96:eb  2cfedad3a6
BLE_ANDROID_DEVICE_CONNECT		63:0c:7f:67:be:d5  2cfe00aa48
------------------ Bluetooth Low Energy (BLE) Attacks Detected (27 Advertisements) --------------------

```
