### ISSUE TITLE
Unable to run wall of flippers

### ISSUE THREAD

**Issue by ralphiedawg** [K3YOMI/Wall-of-Flippers#8]
I am running debian on arm64 host. Each time I try to boot wof, I receive this in console:
[!] Wall of Flippers >> Starting Wall of Flippers

```
Traceback (most recent call last):
  File "/home/debian/Wall-of-Flippers/WallofFlippers.py", line 638, in <module>
    ble_adapters = [adapter for adapter in os.listdir('/sys/class/bluetooth/') if 'hci' in adapter]
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/bluetooth/'
```

Honestly, no clue how to fix this.

**Comment by K3YOMI** [comment]
Do you have a BT adapter?

Check: systemctl status bluetooth

**Comment by ralphiedawg** [comment]
@K3YOMI 
```
Unit bluetooth.service could not be found.
````
Does this mean I need to purchase a USB Bluetooth adapter, and use that in addition to the VM?

**Comment by K3YOMI** [comment]
> @K3YOMI
> 
> ```
> Unit bluetooth.service could not be found.
> ```
> 
> Does this mean I need to purchase a USB Bluetooth adapter and use that in addition to the VM?

This can happen if your system doesn't have Bluetooth support, or if the Bluetooth service is not properly installed or configured. I would double check your current chipset or if you have BT support. This could also be linked to a driver.

**Comment by ralphiedawg** [comment]
@K3YOMI I found out that UTM, my VM service, does not support Bluetooth passthrough. It would work if I was to use a Bluetooth USB adapter and pass that through. I appreciate your help though.
